name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.8
  - menuinst
  - console_shortcut
  - powershell_shortcut
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - navigator-updater
  - holoviews
  - jupyterlab
  - hvplot
  - xarray
  - pandas
  - numpy
